// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizza.DbContexts;

namespace Pizza.Migrations
{
    [DbContext(typeof(PizzaDbContext))]
    partial class PizzaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pizza.Entities.Adresses", b =>
                {
                    b.Property<int>("Num_Adresse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Num_Quartier")
                        .HasColumnType("int");

                    b.HasKey("Num_Adresse");

                    b.HasIndex("Num_Quartier");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("Pizza.Entities.BonLiv", b =>
                {
                    b.Property<int>("Num_Bon_Liv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_Liv")
                        .HasColumnType("datetime2");

                    b.Property<int>("Num_Cde_Cli")
                        .HasColumnType("int");

                    b.Property<int>("Num_Fact")
                        .HasColumnType("int");

                    b.HasKey("Num_Bon_Liv");

                    b.HasIndex("Num_Cde_Cli");

                    b.HasIndex("Num_Fact");

                    b.ToTable("BonLiv");
                });

            modelBuilder.Entity("Pizza.Entities.Catalogue_Pizza", b =>
                {
                    b.Property<int>("Num_Pizza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom_Pizza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prix_Pizza")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Taille_Pizza")
                        .HasColumnType("int");

                    b.HasKey("Num_Pizza");

                    b.ToTable("Catalogue_Pizza");
                });

            modelBuilder.Entity("Pizza.Entities.CdeCli", b =>
                {
                    b.Property<int>("Num_Cde_Cli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_Cde")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Livre_Emporte")
                        .HasColumnType("bit");

                    b.Property<int>("Num_Cli")
                        .HasColumnType("int");

                    b.HasKey("Num_Cde_Cli");

                    b.HasIndex("Num_Cli");

                    b.ToTable("CdeCli");
                });

            modelBuilder.Entity("Pizza.Entities.Client", b =>
                {
                    b.Property<int>("Num_Cli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom_Cli")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Num_Cli");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Pizza.Entities.Detail_Liv", b =>
                {
                    b.Property<int>("Num_Detail_Bon_Liv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addresse_Liv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Num_Bon_Liv")
                        .HasColumnType("int");

                    b.Property<int>("Num_Liv")
                        .HasColumnType("int");

                    b.Property<int>("Num_Quartier")
                        .HasColumnType("int");

                    b.HasKey("Num_Detail_Bon_Liv");

                    b.HasIndex("Num_Bon_Liv");

                    b.HasIndex("Num_Liv");

                    b.ToTable("Detail_Liv");
                });

            modelBuilder.Entity("Pizza.Entities.Fabrication", b =>
                {
                    b.Property<int>("Num_Fab")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_Fab")
                        .HasColumnType("datetime2");

                    b.Property<int>("Num_Pizza")
                        .HasColumnType("int");

                    b.Property<int>("Quant_Fab")
                        .HasColumnType("int");

                    b.HasKey("Num_Fab");

                    b.HasIndex("Num_Pizza");

                    b.ToTable("Fabrication");
                });

            modelBuilder.Entity("Pizza.Entities.Fact_Cli_BonLiv", b =>
                {
                    b.Property<int>("Num_Fact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_Fact_Cli")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Montant_Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Num_Cli")
                        .HasColumnType("int");

                    b.HasKey("Num_Fact");

                    b.HasIndex("Num_Cli");

                    b.ToTable("Fact_Cli_BonLiv");
                });

            modelBuilder.Entity("Pizza.Entities.Ligne_Cde_Cli", b =>
                {
                    b.Property<int>("Num_Ligne_Cde")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Num_Cde_Cli")
                        .HasColumnType("int");

                    b.Property<int>("Num_Pizza")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Num_Ligne_Cde");

                    b.HasIndex("Num_Cde_Cli");

                    b.HasIndex("Num_Pizza");

                    b.ToTable("Ligne_Cde_Cli");
                });

            modelBuilder.Entity("Pizza.Entities.Livraison", b =>
                {
                    b.Property<int>("Num_Liv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_Arrive")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_Depart")
                        .HasColumnType("datetime2");

                    b.Property<int>("Num_Quartier")
                        .HasColumnType("int");

                    b.HasKey("Num_Liv");

                    b.HasIndex("Num_Quartier");

                    b.ToTable("Livraison");
                });

            modelBuilder.Entity("Pizza.Entities.Livreur", b =>
                {
                    b.Property<int>("Num_Liv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom_Livreur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Num_Quartier")
                        .HasColumnType("int");

                    b.HasKey("Num_Liv");

                    b.HasIndex("Num_Quartier")
                        .IsUnique();

                    b.ToTable("Livreur");
                });

            modelBuilder.Entity("Pizza.Entities.Paiement_Cli", b =>
                {
                    b.Property<int>("Num_Piece_Compt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_Paiement")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Montant_Paiement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Num_Fact")
                        .HasColumnType("int");

                    b.HasKey("Num_Piece_Compt");

                    b.HasIndex("Num_Fact");

                    b.ToTable("Paiement_Cli");
                });

            modelBuilder.Entity("Pizza.Entities.Quartier", b =>
                {
                    b.Property<int>("Num_Quartier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom_Quartier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Num_Quartier");

                    b.ToTable("Quartier");
                });

            modelBuilder.Entity("Pizza.Entities.Adresses", b =>
                {
                    b.HasOne("Pizza.Entities.Quartier", "Quartier")
                        .WithMany()
                        .HasForeignKey("Num_Quartier")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Pizza.Entities.BonLiv", b =>
                {
                    b.HasOne("Pizza.Entities.CdeCli", "CdeCli")
                        .WithMany()
                        .HasForeignKey("Num_Cde_Cli")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Pizza.Entities.Fact_Cli_BonLiv", "Fact_Cli_BonLiv")
                        .WithMany()
                        .HasForeignKey("Num_Fact")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Pizza.Entities.CdeCli", b =>
                {
                    b.HasOne("Pizza.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("Num_Cli")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Pizza.Entities.Detail_Liv", b =>
                {
                    b.HasOne("Pizza.Entities.BonLiv", "BonLiv")
                        .WithMany()
                        .HasForeignKey("Num_Bon_Liv")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Pizza.Entities.Livraison", "Livraison")
                        .WithMany()
                        .HasForeignKey("Num_Liv")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Pizza.Entities.Fabrication", b =>
                {
                    b.HasOne("Pizza.Entities.Catalogue_Pizza", "Catalogue_Pizza")
                        .WithMany()
                        .HasForeignKey("Num_Pizza")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Pizza.Entities.Fact_Cli_BonLiv", b =>
                {
                    b.HasOne("Pizza.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("Num_Cli")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Pizza.Entities.Ligne_Cde_Cli", b =>
                {
                    b.HasOne("Pizza.Entities.CdeCli", "CdeCli")
                        .WithMany()
                        .HasForeignKey("Num_Cde_Cli")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Pizza.Entities.Catalogue_Pizza", "Catalogue_Pizza")
                        .WithMany()
                        .HasForeignKey("Num_Pizza")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Pizza.Entities.Livraison", b =>
                {
                    b.HasOne("Pizza.Entities.Quartier", "Quartier")
                        .WithMany()
                        .HasForeignKey("Num_Quartier")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Pizza.Entities.Livreur", b =>
                {
                    b.HasOne("Pizza.Entities.Quartier", "Quartier")
                        .WithMany()
                        .HasForeignKey("Num_Quartier")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Pizza.Entities.Paiement_Cli", b =>
                {
                    b.HasOne("Pizza.Entities.Fact_Cli_BonLiv", "Fact_Cli_BonLiv")
                        .WithMany()
                        .HasForeignKey("Num_Fact")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
